apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodata-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodata-extractor
  template:
    metadata:
      labels:
        app: autodata-extractor
    spec:
      containers:
      - name: autodata-extractor
        image: 637423316857.dkr.ecr.us-west-2.amazonaws.com/autodata-extractor:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: autodata-extractor-service
spec:
  type: LoadBalancer
  selector:
    app: autodata-extractor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
